### ISSUE TITLE
After using the new update error stop my checkout page 

### ISSUE THREAD

**Issue by helalbookmark** [payfort/magento2-payfort#6] opened 2016-10-19 17:33 UTC
After using the new update error stop my checkout page :

`TypeError: window.checkoutConfig.payment.payfortFort.payfort_fort_cc is undefined`

**Comment by DeyaZ88** [comment] 2016-10-20 09:28
Try to flush javascript/css cache & static files cache then flush magento cache.

**Comment by msliman** [comment] 2017-02-14 08:46
I tried to flush javascript/css and magento cache, but still have this error and stopped my checkout page.
please help.

**Comment by mohannadsaleh** [comment] 2017-02-14 16:17
Hi ,

It seems that javascript files which the plugin require is not included , and its related t cache on the system 

can you please try to perform the below 

php bin/magento module:disable --clear-static-content Payfort_Fort
bin/magento setup:upgrade

php bin/magento module:enable --clear-static-content Payfort_Fort
bin/magento setup:upgrade

if you still face the same issue , please do the below commands 

rm -rf var/cache/* var/generation/* pub/static/* var/view_preprocessed/*
rm -rf pub/static/frontend/Magento/luma/en_US/Payfort_Fort/*
php bin/magento module:disable --clear-static-content Payfort_Fort
bin/magento setup:upgrade

php bin/magento module:enable --clear-static-content Payfort_Fort
bin/magento setup:upgrade


Best Regards,

**Comment by msliman** [comment] 2017-02-15 10:04
Hi Mohannad,

Thank you for your reply.
I tried to run the commands above which you mentioned in vain, but when enable CREDIT/DEBIT CARDS payment method from backend, the error was gone and the checkout page is working. The problem is I want to use SADAD payment method only and I enabled it but not appearing in front end. please check the attachments.
![payfort_backend](https://cloud.githubusercontent.com/assets/3694009/22968946/9bcd9200-f37d-11e6-9a20-1af6ae4a8221.png)
![payfort_frontend](https://cloud.githubusercontent.com/assets/3694009/22968947/9bd7213a-f37d-11e6-8b49-0db37529c399.png)

I am asking how to show SADAD payment method, how it is working and is it has a relation to CREDIT/DEBIT CARDS ?

Best Regards,
Mahmoud

**Comment by mohannadsaleh** [comment] 2017-02-15 20:09
Thank you very much for your comments and feedback , we have launched a fix for this issue 

Now u will be able to enable only one payment option without having the same issue .

Please pull latest code and let us know if you need more clarifications or assistance 

Best Regards 
Mohannad Saleh

**Closed** 2017-02-15 20:10 UTC

**Comment by msliman** [comment] 2017-02-16 10:47
Dear Mohannad,

Thank you for your quickly support. It done now perfectly.
If I can ask Is there is a test account for merchant identifier and rest of configurations, so I can test as I can't access payfort  website and now I got 404 error

http://myhost.com/checkout/undefined

 although I was able to access it yesterday before reinstalling the module.

BR,
Mahmoud

**Comment by mohannadsaleh** [comment] 2017-02-16 19:25
Hi Mahmoud, 

I have added our integration@payfort.com team in the email thread, they will be able to provide you with the account and integration settings needed .

regarding the undefined URL , can you please give more details about this , what is the payment options active also did u configure any ? Did you remove the cache using same commands provided before ?

Can you please try to configure SADAD then try to checkout using this payment option and let us know the result 

Again thank you for your feedback 
Best Regards,
Mohannad Saleh

**Comment by msliman** [comment] 2017-02-18 21:11
Hi Mohannad,
Thank you for your help, also the integration team.

My configuration were :command: PURCHAUSE

For the cache, after reinstallation, I didn't remove the cache with those commands you sent to me, just followed those in the module page on Github.


Already, I am using SADAD only now.
BR,Mahmoud

 

    On Thursday, February 16, 2017 10:25 PM, Mohannad Saleh <notifications@github.com> wrote:
 

 Hi Mahmoud,I have added our integration@payfort.com team in the email thread, they will be able to provide you with the account and integration settings needed .regarding the undefined URL , can you please give more details about this , what is the payment options active also did u configure any ? Did you remove the cache using same commands provided before ?Can you please try to configure SADAD then try to checkout using this payment option and let us know the resultAgain thank you for your feedback
Best Regards,
Mohannad Saleh—

**Comment by mohannadsaleh** [comment] 2017-02-19 13:47
Hi ,

Thanks , we have simulated the issue , and handled the issue you are facing , 
Please use latest plugin with fixes and clear cache , this should fix the "undefined" issue you are facing .

Thank you very much for your prompt feedback . 
Best Regards, 
Mohannad Saleh
